In [1]:
import numpy as np

## NUMPY ARRAY AND BASICS 


In [2]:
vec = np.array([1,2,3])

In [3]:
vec

array([1, 2, 3])

In [4]:
matrix = np.array([[1,2,3],
                    [5,6,7]])

In [5]:
matrix

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
matrix.dtype

dtype('int64')

In [7]:
tensor = np.array([[[1,2,3],[4,5,6]]])

In [8]:
tensor

array([[[1, 2, 3],
        [4, 5, 6]]])

"ARRAY PRORPERTIES"


In [9]:
arr = np.array([[1,2,3,],
                [4,5,9]])

In [10]:
print(arr.shape)

(2, 3)


In [11]:
print(arr.ndim)

2


In [12]:
print(arr.size)

6


In [13]:
arr.dtype

dtype('int64')

## ARRAY RESHAPING 

    

In [14]:
arr1 = np.arange(12)

In [15]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
reshaped = arr1.reshape((3,4))

In [17]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
flattened = reshaped.flatten()

In [19]:
ravled = reshaped.ravel()

In [20]:
ravled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

RAVEL = VIEW DETA INSTEAD OF COPY & FLATTEN

#TRANSPOSE 

In [21]:
TRANSPOSE = reshaped.T

In [22]:
TRANSPOSE

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [23]:
np.random.rand(3,4)

array([[0.8598347 , 0.93371733, 0.59023278, 0.14371512],
       [0.45255566, 0.28253522, 0.27456703, 0.55567899],
       [0.99553197, 0.18716472, 0.70290382, 0.00311729]])

In [24]:
np.random.random((3,5))

array([[0.9723366 , 0.40449938, 0.07443015, 0.4473252 , 0.0290216 ],
       [0.28009799, 0.33186862, 0.97500766, 0.15783729, 0.27610111],
       [0.98342551, 0.99195822, 0.33871497, 0.80440547, 0.50480093]])

In [25]:
np.random.randint(100,1000,(4,5))

array([[774, 739, 878, 845, 757],
       [260, 876, 749, 324, 901],
       [938, 730, 843, 670, 489],
       [426, 407, 381, 944, 568]], dtype=int32)

In [26]:
test1 = np.array([[1,2,3],[4,5,6]])

In [27]:
test1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
reeaver = test1.ravel() # shallow copy

In [31]:
reeaver[0] = 100

In [34]:
reeaver

array([100,   2,   3,   4,   5,   6])

In [33]:
test2 = np.array([[1,2,3],[4,5,6]])

In [35]:
flattend = test2.flatten()

In [36]:
test2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
flattend

array([1, 2, 3, 4, 5, 6])

In [38]:
flattend[0] = 0

In [39]:
flattend

array([0, 2, 3, 4, 5, 6])

In [40]:
test2

array([[1, 2, 3],
       [4, 5, 6]])