    __NUMPY ARRAY OPERATIONS__    

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,6,7,8,9,7])

In [3]:
arr

array([1, 2, 3, 6, 7, 8, 9, 7])

In [4]:
arr[0]

np.int64(1)

In [5]:
arr[2:7:2]

array([3, 7, 9])

In [6]:
arr[::-1]

array([7, 9, 8, 7, 6, 3, 2, 1])

In [7]:
matrix = np.array([[1,2,3],[4,5,6]])

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix[0][1]

np.int64(2)

In [10]:
matrix[0]

array([1, 2, 3])

In [57]:
matrix[:,2]

array([3, 6])

**SORTING**


In [12]:
us = np.array([9,8,7,6,5,4,3,2,1,0])

In [13]:
us

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
np.sort(us)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr_2dus = np.array([[6,5,4],[3,2,1],[9,8,7]])

In [61]:
np.sort(arr_2dus,axis=1) 

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

**FILTER**


In [63]:
num = np.array([1,2,3,4,5,6,7,8,9,10])

In [64]:
even = num[num % 2 == 0]

In [65]:
even

array([ 2,  4,  6,  8, 10])

**FILTER WITH MASK**

In [70]:
ARR = np.array([1,2,3,4,5,6,10,22,45,61])

In [71]:
mask = ARR > 5


In [76]:
ARR[mask]

array([ 6, 10, 22, 45, 61])

**FANCY INDEX VS NP.WHERE()**

In [22]:
indices = [0,2,4]

In [23]:
print(num[indices])

[  1   3 400]


In [80]:
newarr = np.array([1,2,3,4,5,6,7,8,9])

In [81]:
wh_py = np.where(newarr>5)

In [82]:
wh_py

(array([5, 6, 7, 8]),)

In [84]:
con_array = np.where(newarr>7,"true","false")

In [85]:
con_array

array(['false', 'false', 'false', 'false', 'false', 'false', 'false',
       'true', 'true'], dtype='<U5')

In [26]:
condition_array = np.where(num>5,"true","false")

In [27]:
condition_array

array(['false', 'false', 'false', 'true', 'true', 'true', 'true', 'true',
       'true'], dtype='<U5')

### ADDING AND REMOVING DATA

In [28]:
a1 = np.array([1,2,3,4])


In [29]:
a2 = np.array([5,6,7,8])

In [30]:
comb = np.concatenate((a1,a2))

In [31]:
comb

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a1.shape

(4,)

In [33]:
comb.shape

(8,)

In [34]:
matrix.shape

(2, 3)

In [35]:
matrix


array([[1, 2, 3],
       [4, 5, 6]])

**ARRAY COMPATIBILITY**

In [36]:
a1 = np.array([1,2,3])

In [86]:
a2 = np.array([4,5,6])

In [88]:
a1.shape == a2.shape

True

In [42]:
original = np.array([[1,2],[3,4]])

In [43]:
nr = np.array([[5,6]])

In [89]:
newstack = np.vstack((original,nr))

In [91]:
newstack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
original

array([[1, 2],
       [3, 4]])

In [47]:
col = np.array([[7],[8]])

In [48]:
new_col = np.hstack((original,col))

In [49]:
original

array([[1, 2],
       [3, 4]])

In [50]:
new_col

array([[1, 2, 7],
       [3, 4, 8]])

In [51]:
arr = np.array([1,2,3,4,5,6])

In [52]:
deleted = np.delete(arr,0)

In [53]:
deleted

array([2, 3, 4, 5, 6])

In [54]:
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr


array([1, 2, 3, 4, 5, 6])